%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
SerialNumber: "DA6371162" # Not needed for single camera. Specify serial number for multiple cameras. 
#SerialNumber: "DA5148678" 
TopicName: "left_camera/image"

TriggerEnable: 0 # 0 stands for Off, 1 stands for On
#ExposureAutoMode: 0 # 0 stands for Off, 1 stands for Once, 2 stands for Continues
#ExposureTime: 500 # us

Brightness: 70
Binning: 2
PTPEnable: 1 # PTP Enable, 0 stands for Off, 1 stands for On
# ReverseY:1
# ReverseX:1
ExposureAutoMode: 2
AutoExposureTimeLower: 100
AutoExposureTimeUpper: 5000

image_scale: 1 # 1 0.5
GainAuto: 2 # Gain Auto, 0 stands for Off, 1 stands for Once, 2 stands for Continues
Gain: 15 # min: 0   max: 17.0166
Gamma: 0.7  # min: 0   max: 17.0166
GammaSelector: 1 # 0 stands for user, 1 stands for sRGB
# GammaEnable: 1

#PixelFormat: 6 #0: RGB8, 1: BayerRG8, 2: BayerRG12Packed, 3: BayerGB12Packed, 4: BayerGB8
